version: '3.8'
services:
  # mongo:
  #   image: mongo:latest
  #   container_name: activity-booking
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  #     - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
  #   ports:
  #     - "${MONGO_PORT}:27017"
  #   restart: unless-stopped
  #   volumes:
  #     - mongo_data:/data/db
  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   healthcheck:
  #     test: ["CMD", "mongosh", "--eval", "'db.adminCommand(\"ping\").ok'", "--quiet"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: activity-booking-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
    restart: unless-stopped
    networks:
      - app-network
    # depends_on:
    #   - mongo

networks:
  app-network:
    driver: bridge 

volumes:
  mongo_data: 