version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: activity-booking-app
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-5000}
      - MONGODB_URI=${MONGODB_URI:-mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRE=${JWT_EXPIRE:-30d}
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env

  mongo:
    image: mongo:latest
    container_name: activity-booking-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-example}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-activity-booking}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

volumes:
  mongo_data: 